config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :lists do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list, counter_cache: true

  validates :body, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.create(item_params)
    redirect_to list_path(@list)
  end

  private

  def item_params
    params.require(:item).permit(:body)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update(list_params)
      redirect_to @list
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= form_with model: [ @list, @list.items.build ] do |form| %>
  <p>
    <%= form.label 'tarefa' %><br>
    <%= form.text_field :body %>
  </p>
  <p>
    <%= form.submit 'Criar' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with model: list do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @list.errors.full_messages_for(:title).each do |message| %>
      <%= message %>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<br/>
<b>Editando lista</b>

<%= render "form", list: @list %>

app/views/lists/index.html.erb
<h1>ToDo Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.title, list %>
      <%= list.items_count %>
    </li>
  <% end %>
</ul>

<%= link_to "Criar lista de tarefas", new_list_path %>

app/views/lists/new.html.erb
<br/>
<b>Criando lista</b>

<%= render "form", list: @list %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>

<ul>
<% @list.items.each do |item| %>
  <li> <%= item.body %> </li>
<% end %>
</ul>

<ul>
  <li><%= link_to "voltar", lists_path %></li>
  <li><%= link_to "editar", edit_list_path(@list) %></li>
  <li><%= link_to "deletar", list_path(@list), method: :delete %></li>
</ul>

<b>Adicionando items para fazer:</b>
<%= render 'items/form' %>